version: "3"
networks:
  gitea:
    external: true
services:
  server:
    image: docker.gitea.com/gitea:1.23.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
  runner:
    image: docker.io/gitea/act_runner:nightly
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "http://server:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "vSjSgPALgaKtByISIj9Ff3SB3kzL9DUUvN7nbpyB"
      GITEA_RUNNER_NAME: "runner-1"
    volumes:
      - ./config.yaml:/config.yaml
      - ./data:/data
      - ./cache:/root/.cache
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8088:8088
    networks:
      - gitea